# -*- coding: utf-8 -*-
"""Filtros en el dominio del espacio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bweWQPev6KrF5wI-5tFg7A1h1jcxJXPI
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np


ruta = r'C:\Fundamentos-de-Procesamiento-Digital-de-Imagenes\Imagenes\salt-snoopy.png' # snoopy salt


ima_rgb = cv2.imread(ruta)
ima_grises = cv2.cvtColor(ima_rgb, cv2.COLOR_BGR2GRAY)



""" Padding en las imagenes  """

def padding(imagen, dx):
  y, x = imagen.shape
  paddineada = np.zeros((int(y + dx/2 + 1), int(x + dx/2 + 1)))
  for j in range(y):
    for i in range(x):
      paddineada[int(j + dx/2)][int(i + dx/2)] = imagen[j][i]
  return np.array(paddineada)


"""###### Filtro de la media ######### """

def media_matrix(matrix):
  y, x = matrix.shape
  N = y * x
  media = 0
  for j in range(y):
    for i in range(x):
      media += matrix[j][i]
  media = media / N
  return media

def media_matrix_metodo2(matrix):
  N = 0
  media = 0
  for j in matrix:
    for i in j:
      media += i
      N += 1
  media = media / N
  return media

def aplica_filtro_media(image, filtro_ap, lado_cuadrado):
  # Ciclo para aplicar el filtro sobre la imagen:
  y, x = ima_grises.shape
  ima_padding = padding(ima_grises, lado_cuadrado)
  yp, xp = ima_padding.shape
  ima_filtrada = np.zeros((y, x))
  cuadrado_temp_delaimag = np.zeros((lado_cuadrado, lado_cuadrado))
  for j in range(y-lado_cuadrado+1): # Fila
    for i in range(x-lado_cuadrado+1): # Columna
      #Entramos a la sección específica de la imagen (rectángulo)
      for k in range(lado_cuadrado):
        for l in range(lado_cuadrado):
          cuadrado_temp_delaimag[k][l] = ima_padding[j + k][i + l]
      filtro = filtro_ap(cuadrado_temp_delaimag)
      ima_filtrada[j][i] = filtro
  return ima_filtrada

ima_filtrada = aplica_filtro_media(ima_grises, media_matrix, 3)

"""###### Filtro Gaussiano ######"""

def gaussian_kernel(size, sigma):
    # El tamaño del kernel debe ser impar para tener un centro
    if size % 2 == 0:
        raise ValueError("El tamaño del kernel debe ser un número impar")

    kernel = np.zeros((size, size))
    center = size // 2

    for y in range(size):
        for x in range(size):
            # Coordenadas relativas al centro del kernel
            rel_x = x - center
            rel_y = y - center

            # Fórmula Gaussiana 2D
            kernel[y][x] = (1 / (2 * np.pi * sigma**2)) * np.exp(-(rel_x**2 + rel_y**2) / (2 * sigma**2))

    # Normalizar el kernel para que la suma de sus elementos sea 1
    # Esto asegura que la intensidad general de la imagen no cambie
    return kernel / np.sum(kernel)


def applica_gaussian_filter(image, kernel_size, sigma):
    # Generar el kernel Gaussiano
    kernel = gaussian_kernel(kernel_size, sigma)

    # Obtener dimensiones de la imagen y del kernel
    img_height, img_width = image.shape
    kernel_height, kernel_width = kernel.shape

    # Calcular el padding necesario
    pad_height = kernel_height // 2
    pad_width = kernel_width // 2

    # Crear una imagen con padding de ceros
    padded_image = np.pad(image, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant', constant_values=0)

    # Crear una imagen para almacenar el resultado filtrado
    filtered_image = np.zeros_like(image, dtype=float)

    # Aplicar la convolución
    for y in range(img_height):
        for x in range(img_width):
            # Extraer la región de la imagen que coincide con el kernel
            region = padded_image[y:y + kernel_height, x:x + kernel_width]

            # Multiplicar la región por el kernel y sumar los resultados (convolución)
            filtered_image[y, x] = np.sum(region * kernel)

    return filtered_image.astype(np.uint8)

# Parámetros del filtro Gaussiano
kernel_size = 17  # Debe ser impar, por ejemplo 3, 5, 7...
sigma = 1.0     # Desviación estándar

# Aplicar el filtro Gaussiano a la imagen en escala de grises
ima_gaussiana = applica_gaussian_filter(ima_grises, kernel_size, sigma)

"""###### Filtro de la mediana ######"""

def insertion_sort(arr):
    key = 1
    lon_arr = len(arr)
    key = 1
    # arr_tem = [0]*lon_arr
    for i in range(lon_arr):
      for j in range(key):
        if arr[j] < arr[i]:
          temp = arr[i]
          arr[i] = arr[j]
          arr[j] = temp
      key += 1
    return arr

def aplanado_arreglo(matrix):
  # Aplanamos la matriz de valores
  y, x = matrix.shape
  arr = [0]*(y*x)
  for j in range(y):
    for i in range(x):
      arr[j * x + i] = matrix[j][i]
  return np.array(arr)

def mediana_artesanal(matrix):
  # Aplanamos la matriz de valores
  arr = aplanado_arreglo(matrix)
  # Los acomodamos
  arr = insertion_sort(arr)
  longitud = len(arr)
  # Obtenemos el índice donde está la mitad de datos (50%)
  temp = 0
  while temp < longitud/2:
    temp += 1
  return arr[int(temp)]

"""## Aplicación del filtro"""

def mediana_filtro(imagen, kernel_size):
    # El tamaño del kernel debe ser impar para tener un centro
    if kernel_size % 2 == 0:
        raise ValueError("El tamaño del kernel debe ser un número impar")

    img_height, img_width = imagen.shape
    pad_size = kernel_size // 2

    # Crear una imagen con padding para manejar los bordes
    padded_image = padding(imagen, kernel_size)

    filtered_image = np.zeros_like(imagen, dtype=np.uint8)

    # Aplicar el filtro de la mediana
    for y in range(img_height):
        for x in range(img_width):
            # Extraer la región de la imagen que coincide con el kernel
            region = padded_image[y:y + kernel_size, x:x + kernel_size]

            # Calcular la mediana de los valores en la región
            filtered_image[y, x] = mediana_artesanal(region)

    return filtered_image

# Parámetros del filtro de la mediana
kernel_size_median = 3 # Debe ser impar, por ejemplo 3, 5, 7...

# Aplicar el filtro de la mediana a la imagen en escala de grises
ima_mediana = mediana_filtro(ima_grises, kernel_size_median)
"""# Todos los métodos juntos"""

fig, axs = plt.subplots(1, 4, figsize=(30, 6))

axs[0].imshow(ima_grises, cmap = 'gray')
axs[0].set_title('Imagen original')
axs[1].imshow(ima_filtrada, cmap = 'gray')
axs[1].set_title('Imagen con filtro media')
axs[2].imshow(ima_gaussiana, cmap='gray')
axs[2].set_title(f'Imagen con Filtro Gaussiano (size={kernel_size}, sigma={sigma})')
axs[3].imshow(ima_mediana, cmap='gray')
axs[3].set_title(f'Imagen con Filtro de la Mediana (size={kernel_size_median})')
plt.show()

